== Checkout Kata

=== The problem

Implement the code for a supermarket checkout that calculates the total price of a number of items.


In a normal supermarket, items are identified by "stock keeping units" or "SKUs". In our store, we will use
individual letters of the alphabet, A, B, C etc, as the SKUs. Our goods are priced individually. In addition,
some items are multipriced: buy _n_ of them and which will cost you _y_. For example, item A might cost 50
pence individually but this week we have a special offer where you can buy 3 As for £1.30.


This week's prices are the following:


[options="header"]
|=======================
|Item |Unit Price | Special Price
|A    |50         |3 for 130
|B    |30         |2 for 45
|C    |20         |
|D    |15         |
|=======================


Our checkout accepts items in any order so if we scan a B, then an A, then another B, we will recognise
the two B's and price them at 45 (for a total price so far of 95).


Extra points: Because the pricing changes frequently we will need to be able to pass in a set of pricing
rules each time we start handling a checkout transaction.

=== Instructions

This is a gradle project. Standard practices apply.

To run the tests (on Windows)

```
gradlew test acceptanceTest
```

To run the application

```
gradlew build
java -jar build\libs\checkout-kata.jar
```

You will type the products one by one e.g. _A_, and press enter. The application with throw a message if an invalid or empty product is entered. Type END and press enter when you are done. Valid products are _A, B, C, D_. Pricing rules can be found at `src\main\resources\pricing_rules.csv`.

The location of the pricing rules can be overwritten to point to any file. To do so, pass a parameter.

```
java -jar build\libs\checkout-kata.jar C:\Temp\pricing_rules.csv
```

=== Architectural Decision Records (ADR)


A folder with the architectural decisions is available in `\adr`.


Please read that first if you want to understand the asumptions made during this exercise.


=== Outside-In TDD


This exercise has been developed using Outside-In TDD starting with an acceptance test and writing unit tests once the high level feature was outlined, to cover the rest of the edge cases.

As a result there are two folders with tests

- acceptance-test
- test

The commit history will also outline the steps. I have left the different feature branches to provide a better insight into the process. In here there are basically three types of commits, following the RED-GREEN-REFACTOR TDD approach.

- RED: add tests that make the build fail
- GRN: add production code that make the tests pass
- RFT: refactoring

Additionally there are some other commits without a prefix, for things like documentation or minor changes that don't fit anywhere else.


